name: WordPress Plugin CI/CD

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Change to your supported PHP version
          extensions: mbstring, zip
          coverage: none
      
      - name: Install PHPCS
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          chmod +x phpcs.phar
          sudo mv phpcs.phar /usr/local/bin/phpcs

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, zip
          coverage: xdebug

      - name: Setup WordPress
        run: |
          curl -o /tmp/wordpress.tar.gz https://wordpress.org/latest.tar.gz
          tar -xzf /tmp/wordpress.tar.gz -C /tmp/
          mv /tmp/wordpress /tmp/wordpress-latest

      - name: Download PHPUnit
        run: |
          wget https://phar.phpunit.de/phpunit-9.phar
          chmod +x phpunit-9.phar
          mv phpunit-9.phar /usr/local/bin/phpunit

      - name: Run PHPUnit Tests
        env:
          WP_TESTS_DIR: /tmp/wordpress-latest
        run: phpunit
